### ISSUE TITLE
how to understand  sereval environments

### ISSUE THREAD

**Issue by yangtianyong** [jerabaul29/Cylinder2DFlowControlDRLParallel#3]
Hello:
        I wonder several environments means the fluid environments that the CFD simulated?And those independent envieonments feeds data to the same ANN?Also we can use several computers to simulate the environments,but train only one ANN?
       Thank you for your answering !
Best wishes!

**Comment by jerabaul29** [comment]
Hi,

- all environments here are completely independent of each other, and can be run completely in parallel

- there is one single network that centralizes all the training data from all the environments.

So as you say, you can use several computers to simulate the environments, and one single computer to train the ANN. This is actually what I and my group have been doing for a while.

This is made easy here because we use simple sockets, which can talk across hosts and processes. The thing with sockets is that they are slow, but since there is only little data exchanged now and then, it is not an issue (most time is in the CFD anyways, even with the slow sockets).

I had started to put a bit of 'tunelling material' online for explaining here:

https://github.com/jerabaul29/Cylinder2DFlowControlDRLParallel/tree/master/tunneling_scripts

I can re-format it and make it more accessible, will let you know when it happens.

**Comment by jerabaul29** [comment]
@yangtianyong I have updated quite a lot the material about training across machines, should be much easier to follow / understand. Can you have a look at the 'learning howto' material here first:

https://github.com/jerabaul29/Cylinder2DFlowControlDRLParallel/tree/master/tunneling_scripts/learning_to_tunnel

This should make you understand the general idea behind.

Then to make it work in practice with this code, can you have a look at / follow the detailed explanations here:

https://github.com/jerabaul29/Cylinder2DFlowControlDRLParallel/tree/master/tunneling_scripts/training_across_network

This has been used by several people including myself, so quite sure it should work, but let me know if anything is unclear or does not work :) .
