### ISSUE TITLE
Can we use mpirun to accelerate the env calculation?

### ISSUE THREAD

**Issue by nicehiro** [jerabaul29/Cylinder2DFlowControlDRLParallel#6]
Hi, I found Fenics script can be parallel running by using` mpirun -np 64 python script.py` from [https://fenicsproject.org/](here).

But I failed.
![image](https://user-images.githubusercontent.com/17773634/129708884-18c1b6fc-65b4-46ab-bc37-2f15f56ef72d.png)

Could you help me solve this problem? Cause I don't familiar with the fenics.
Thanks!

**Comment by jerabaul29** [comment]
We had tried on this specific code to parallelize the CFD (we had a parallel solver running etc), but found out that the problem was too small to get interesting speedups; with 2 cpus, we were getting something like 1.5 speedup, and with 3 cpus getting no more gains or even lower performance. But in 3D cases, when the CFD gets very expensive, it would be worth to parallelize :) .

**Comment by nicehiro** [comment]
@jerabaul29 Yes, I found that later in your paper, so I close the issue.

Sorry to bother you.

**Comment by jerabaul29** [comment]
No worries :) . This is a natural question, and definitely the way to go in 3D: combine parallelization of the CFD (with N cores each, being as many cores per CFD simulation as provides good scaling), but since you may likely (at least for moderate Re cases) have more CPUs available on a large machine with several thousands of CPUs than how well your CFD scales, you can combine it with having M such parallelized simulations in parallel, to use N*M CPUs at once.
